logging:
  level:
    org.springframework.security.oauth2: DEBUG
    
eventocache:
  endpoint:
    uri: http://localhost:8585/eventoCache

server:
  port: 8081
  servlet:
    context-path: /auth
    session:
      cookie:
        path: /auth