logging:
  level:
    org.springframework.security.oauth2: DEBUG

security:
  require-ssl: true

server:
  port: 8081
  servlet:
    context-path: /auth
    session:
      cookie:
        path: /auth
  ssl:
    key-store-password: ${authpass}
    key-store: classpath:eventoas.jks
    key-store-type: JKS
    key-alias: authserver
  error:
    whitelabel:
      enabled: false

eventoapp:
  endpoint:
    uri: ${EVENTOAPP_HOST}
    #uri: https://localhost:8443

eventoangular:
  endpoint:
    uri: ${EVENTOANGULAR_HOST}
    #uri: http://localhost:4200